name: custodia
description: Custodia is a home and yard management company for seniors.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gradient_app_bar: ^0.1.3
  flutter_slidable: ^0.5.3
  shared_preferences: ^0.5.3+4
  flutube: ^0.8.1
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  validators: ^2.0.0+1
  http: ^0.12.0+2
  intl: ^0.16.0
  flutter_launcher_icons: ^0.7.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/house.jpg
    - assets/images/pointer.png
    - assets/images/grass.png
    - assets/images/logo.png
    - assets/images/checkmark.png
  fonts:
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/roboto-light.ttf
    - family: RobotoRegular
      fonts:
       - asset: assets/fonts/roboto-regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/roboto-medium.ttf
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/roboto-black.ttf
    - family: NunitoLight
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
    - family: NunitoRegular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: NunitoMedium
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: NunitoBlack
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
